from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
s=s.replace('<title>Creative Design Portfolio</title>','<title>Creative.Marve Portfolio</title>')
s=s.replace('CREATIVE<span class="dot">.</span>DESIGN','CREATIVE<span class="dot">.</span>MARVE')
s=s.replace('Graphic Design Portfolio','Creative.Marve Portfolio')
s=s.replace('href="mailto:hello@example.com">Start a conversation','href="mailto:creative.marve@gmail.com">Send an email')
s=s.replace('.hero{max-width:1180px;margin:auto;padding:90px 24px 70px;display:grid;grid-template-columns:1.1fr .9fr;gap:50px;align-items:center}', '.hero{max-width:1180px;margin:auto;padding:90px 24px 70px;display:grid;grid-template-columns:1fr;gap:38px;align-items:start}.hero>div:first-child{max-width:850px}')
s=s.replace('.heroimg{background:#111;border:1px solid var(--line);border-radius:26px;padding:12px;transform:rotate(2deg);box-shadow:0 25px 80px rgba(0,0,0,.45)}.heroimg img{width:100%;display:block;border-radius:16px}', '.heroimg{width:100%;max-width:1180px;margin:0 auto;background:#111;border:1px solid var(--line);border-radius:26px;padding:12px;box-shadow:0 25px 80px rgba(0,0,0,.45);cursor:pointer}.heroimg img{width:100%;display:block;border-radius:16px;animation:portfolioFloat 7s ease-in-out infinite;transform-origin:center center}')
s=s.replace('.card{background:var(--surface);border:1px solid var(--line);border-radius:18px;overflow:hidden;transition:.25s;cursor:pointer}', '.card{background:var(--surface);border:1px solid var(--line);border-radius:18px;overflow:hidden;transition:.25s;cursor:pointer}.card img{animation:portfolioPulse 6s ease-in-out infinite alternate;transform-origin:center center;transition:filter .35s ease}.card:hover img{filter:brightness(1.08)}.card:nth-child(2n) img{animation-delay:-1.2s}.card:nth-child(3n) img{animation-delay:-2.4s}.card:nth-child(4n) img{animation-delay:-3.6s}@keyframes portfolioFloat{0%,100%{transform:scale(1) translateY(0) rotate(0deg)}50%{transform:scale(1.018) translateY(-5px) rotate(.25deg)}}@keyframes portfolioPulse{0%{transform:scale(1)}100%{transform:scale(1.035)}}')
old='''const grid=document.getElementById('grid');function render(f){f=f||'all';grid.innerHTML=items.filter(x=>f==='all'||x[0]===f).map(x=>'<article class="card" data-img="'+(x[2]-1)+'"><img src="'+imgs[x[2]-1]+'" loading="lazy" alt="'+x[1]+'"><div class="meta"><strong>'+x[1]+'</strong><span>View project</span></div></article>').join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>{document.getElementById('modalimg').src=imgs[c.dataset.img];document.getElementById('modal').classList.add('open')})}'''
new='''const grid=document.getElementById('grid');let audioCtx;function playClick(){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const now=audioCtx.currentTime;const gain=audioCtx.createGain();gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.055,now+.008);gain.gain.exponentialRampToValueAtTime(.0001,now+.16);gain.connect(audioCtx.destination);const osc=audioCtx.createOscillator();osc.type='sine';osc.frequency.setValueAtTime(620,now);osc.frequency.exponentialRampToValueAtTime(880,now+.08);osc.connect(gain);osc.start(now);osc.stop(now+.17)}catch(e){}}function openImage(index){playClick();document.getElementById('modalimg').src=imgs[index];document.getElementById('modal').classList.add('open')}function render(f){f=f||'all';grid.innerHTML=items.filter(x=>f==='all'||x[0]===f).map(x=>'<article class="card" data-img="'+(x[2]-1)+'"><img src="'+imgs[x[2]-1]+'" loading="lazy" alt="'+x[1]+'"><div class="meta"><strong>'+x[1]+'</strong><span>View project</span></div></article>').join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openImage(Number(c.dataset.img)))}'''
if old not in s: raise SystemExit('render block not found')
s=s.replace(old,new)
s=s.replace("document.getElementById('close').onclick=()=>document.getElementById('modal').classList.remove('open');", "document.querySelector('.heroimg').onclick=()=>openImage(0);document.getElementById('close').onclick=()=>document.getElementById('modal').classList.remove('open');")
p.write_text(s,encoding='utf-8')
